### ISSUE TITLE
Help wanted: call for collaborators 

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#1757]
@vsouza @lfarah @miguelarauj1o @naeemshaikh90 @victorgama 

Looks like we are falling behind again on addressing pull requests/issues, let's add more collaborators

Please leave a nomination if you can think of anyone

I vote for @arasu01

**Comment by miguelarauj1o** [comment]
Sorry guys, but I'm very busy these days.
I'll need a couple of months to train for my programming interview.
I can't suggest anyone right now, but we could call @ReadmeCritic.
What do you guys think?

**Comment by lfarah** [comment]
Hey @dkhamsing, I just came back from a 3 month consulting job. I will have waaay more time now to go back and contribute to AwesomeiOS

**Comment by victorgama** [comment]
Hey folks!

Lately I've been really busy working on a project, which left me with no time to go through PRs here. Anyhow, I believe I'll be back in a couple weeks.

PS: Welcome back, @lfarah! 😄

**Comment by vsouza** [comment]
I believe that we're doing an amazing job. All of us have a lot of things to do outside here.  But we always reached goal the main objective here, doing the best curated Awesome-iOS list.

New contributors will always welcome, but I always think in people that have contributed with this list before. So we can search people by contributions and invite them.

I'm not worried about this for now. We have only 4 pull requests open, and some of these we're waiting for modifications.

I believe we can remove on modify the danger alert for redirections, a lot of pull requests have to wait to be integrated because of another link redirection error.

What u think guys?

**Comment by victorgama** [comment]
I agree with @vsouza.

I'd also like to propose we close stale PRs after some inactivity time, say, 5 days. 
(Who opened the closed PR can reopen whenever they want.)

Oh, I will also be iterating our open issues in the next few days.

**Comment by naeemshaikh90** [comment]
Agree with @vsouza and @victorgama .

**Comment by dkhamsing** [comment]
I will update the danger warnings to have a note explaining what has to be done, i.e. Redirects will be fixed by someone else

**Comment by dkhamsing** [comment]
Should we reopen this

**Comment by dkhamsing** [comment]
Reopening

**Comment by dkhamsing** [comment]
Hm maybe it will be better to create a new issue so it sits at the top :)
