### ISSUE TITLE
Dupes

### ISSUE THREAD

**Issue by dkhamsing** [vsouza/awesome-ios#564]
@lfarah hey we got these two projects listed twice pretty close to each other towards the end under Tutorials and Other Awesome Lists.. can we list them once only 

Awesome-Swift-Education - All of the resources for Learning About Swift  :large_orange_diamond:
Awesome-Swift-Playgrounds - A List of Awesome Swift Playgrounds!  :large_orange_diamond:

**Comment by lfarah** [comment]
They present the same thing, but different purposes:
Awesome-Swift education focuses on teaching Swift to people who are still learning
Awesome-Swift Playgrounds has some of these teachings, but also harder things like the Mathematics part, and since playgrounds is AWESOME to teach, this one is awesome because it is only about playgrounds projects, a thing that Swift education lacks

**Comment by dkhamsing** [comment]
Ok

**Comment by dkhamsing** [comment]
Actually you missed the question 

Each project is listed twice 

Once in Tutorials and once in Other Awesome Lists

**Comment by lfarah** [comment]
It kinda makes sense to be in both lists, since they are both Awesome-Lists about tutorials. But we should definitely check with @vsouza what we can do about that.

**Comment by lfarah** [comment]
@dkhamsing thinking again, should go only in tutorials

**Comment by dkhamsing** [comment]
Thanks
