### ISSUE TITLE
Separate into 2 awesome list: Objective-c and Swift

### ISSUE THREAD

**Issue by CavalcanteLeo** [vsouza/awesome-ios#643]
It became a bit disorganized with a lot of content, for me, it will be better if we separate into two awesome list: Awesome-Objective-C and Awesome-Swift

what do you guys think?

**Comment by vsouza** [comment]
over time we will have a smaller number of projects in Objective-C. So we can think of a new organization, at this time :large_orange_diamond: solves.

**Comment by lfarah** [comment]
@CavalcanteLeo the problem with this is that sometimes as a Swift developer, I can't find a Swift library for something I'm looking for, but it doesn't matter for me because I can use an objective-c library instead and it still works perfectly.
It doesn't make sense to divide into 2 lists because in the end, it doesn't matter if it was written on Swift or not.
Because Awesome-iOS has a lot of content, we always try to break into more categories, so it is more organized. One example was our UI Section, that was so big we had to divide into smaller categories like Alert View, Activity Indicator, Button and others.

**Comment by lfarah** [comment]
But it's good that you told us that it became a little bit disorganized. We love to hear from the community and we're always trying to make the repo the best way possible. What were you searching for that made you confused? Let us know!  😀

**Comment by CavalcanteLeo** [comment]
=)

**Comment by vsouza** [comment]
:smile:

**Comment by vsouza** [comment]
guys i'll close this issue, but feel free to reopen at any time it deems necessary.

Thanks :heart:
