### ISSUE TITLE
Show "stars" count or "watch" count for repositories

### ISSUE THREAD

**Issue by moonvader** [vsouza/awesome-ios#756]
First of all - thank you for great job - this list is really awesome. But the more items it has - it becomes harder to user it.
What i really need to know - **is 2 things about repository** (maybe it can be also important for other users) - **how many watches/stars it has and what date it was updated last time**.
I found a lot repositories in this list that have about 5-10 stars/watches and was updated almost 3 years ago.

**Comment by lfarah** [comment]
@moonvader 
As you can see [here](https://github.com/vsouza/awesome-ios/issues/574), we did some cleanup in the repository and only projects with the last commit from less than 2 years ago are accepted. 

We are not perfect and maybe we didn't remove all the old projects so let us know which one doesn't follow [our commit rules](https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md#projects-are-ineligible-if)

About the stars, I always think about this functionality because some other lists use this method, as you can see here [https://github.com/cjwirth/awesome-ios-ui). I wanted to find the cleanest way to do that and the options I found were:

1. Sort the Sections based on stars, which wouldn't be easy since we need a bot to do that
2. Stars badge, as you mentioned, which would look like this

### Animation
 * [Pop](https://github.com/facebook/pop) - An extensible iOS and OS X animation library, useful for physics-based interactions. <br> [![](http://gh-btns.cjwirth.com/stars/facebook/pop)](https://github.com/vsouza/Awesome-iOS/stargazers) <br>
 * [AnimationEngine](https://github.com/intuit/AnimationEngine) - Easily build advanced custom animations on iOS. <br> [![](http://gh-btns.cjwirth.com/stars/intuit/AnimationEngine)](https://github.com/vsouza/Awesome-iOS/stargazers) <br>
 * [Awesome-iOS-Animation](https://github.com/jackyzh/awesome-ios-animation) - Collection of Animation projects <br> [![](http://gh-btns.cjwirth.com/stars/jackyzh/awesome-ios-animation)](https://github.com/vsouza/Awesome-iOS/stargazers) <br>
 * [RZTransitions](https://github.com/Raizlabs/RZTransitions) - A library of custom iOS View Controller Animations and Interactions. <br> [![](http://gh-btns.cjwirth.com/stars/Raizlabs/RZTransitions)](https://github.com/vsouza/Awesome-iOS/stargazers) <br>

**Comment by lfarah** [comment]
@dkhamsing and @vsouza, what do you guys think about this star badge?

**Comment by lfarah** [comment]
@moonvader really thanks for the feedback. We are always thinking about how to make the library search as easy as possible and feedbacks like yours are really important and we take them very seriously.
Thanks a lot for helping! 😃

**Comment by moonvader** [comment]
I think that it can be some table with sorting, searching and filtering
for example - _i want to see all flat UI libraries that have at least 200 stars or viewers_

**Comment by lfarah** [comment]
That's something we'd do on [our website](http://awesomeios.com) ([repo here](https://github.com/vsouza/awesomeios.com)), since we can't do something that smart on a ```README.md```

**Comment by moonvader** [comment]
of course, you can do it on your website.
and use something like DataTables to organize this list.

**Comment by vsouza** [comment]
@moonvader , we've had some discussions about it and it is always valid to raise issues related to the list of improvements. Thanks for the sugestion.

We are currently developing a website to meet some deficiencies we have in repo for limitations of the format we are today.
The website would be the ideal place for more complete information and we are working on it. As the @lfarah said, we have a repository where the site code and any help is always welcome. 😄 
Lately I'm limiting some features in the repository worry about maintaining a "visually clean" list, we now have over 1,000 items listed and insert many badges and information on each item could be problematic.
On the awesome-iOS site roadmap we have tasks to index all this content in databases and be able to perform more specific searches, we will use ElasticSearch or Apache Solr for it. Among other improvements.


BTW: DataTables is a very nice idea. 👍 

Thank you guys.

**Comment by dkhamsing** [comment]
I have seen these star badges, they may make our list really slow to load

**Comment by lfarah** [comment]
Can we close this, guys?

**Comment by vsouza** [comment]
yep 😄
